- name: "创建ssl证书目录"
  file:
    path: "{{ ssl_dir }}"
    state: directory

- stat:
    path: "{{ ssl_dir }}/ca.key"
  register: ca_key
- name: "Generate CA private key"
  when: not ca_key.stat.exists
  openssl_privatekey:
    path: "{{ ssl_dir }}/ca.key"
    type: RSA
    size: 4096
- stat:
    path: "{{ ssl_dir }}/ca.csr"
  register: ca_csr
- name: "Generate CA request"
  when: not ca_csr.stat.exists
  openssl_csr:
    path: "{{ ssl_dir }}/ca.csr"
    privatekey_path: "{{ ssl_dir }}/ca.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: elastic
    basic_constraints_critical: yes
    basic_constraints:
      - CA:TRUE

- stat:
    path: "{{ ssl_dir }}/ca.pem"
  register: ca_pem
- name: "Generate CA certificate"
  when: not ca_pem.stat.exists
  openssl_certificate:
    path: "{{ ssl_dir }}/ca.pem"
    provider: selfsigned
    privatekey_path: "{{ ssl_dir }}/ca.key"
    csr_path: "{{ ssl_dir }}/ca.csr"


- name: "Generate private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/{{ item }}.key"
    type: RSA
    size: 4096
  with_items:
    - "{{ groups['es'] }}"

- name: "Generate request"
  openssl_csr:
    path: "{{ ssl_dir }}/{{ item }}.csr"
    privatekey_path: "{{ ssl_dir }}/{{ item }}.key"
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: elastic
    key_usage_critical: yes
    subject_alt_name: "{{ item | regex_replace('^', 'IP:') }}"
  with_items:
    - "{{ groups['es'] }}"

- name: "Generate certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/{{ item }}.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/{{ item }}.key"
    csr_path: "{{ ssl_dir }}/{{ item }}.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"
  with_items:
    - "{{ groups['es'] }}"