- name: "添加ELK软件源"
  yum_repository:
    file: epel
    name: epel
    description: ELK repository for 7.x packages
    baseurl: "https://mirrors.tuna.tsinghua.edu.cn/elasticstack/7.x/yum/"
    gpgcheck: no
    enabled: yes
  tags: repo
- name: "添加elasticsearch组"
  group:
    name: "elasticsearch"
    gid: "300"
    system: yes
    state: present
  tags: group
- name: "添加elasticsearch用户"
  user:
    name: "elasticsearch"
    uid: "300"
    group: "300"
    createhome: no
    comment: elasticsearch system user
    system: yes
    state: present
  tags: user
- name: "安装elasticsearch"
  yum:
    name: 'elasticsearch{% if version is defined and version != ""  %}-{{ version }}{% endif %}'
    update_cache: yes
    state: present
  tags: install_es
- name: "修改ElasticSearch Systemd"
  block:
    - name: ElasticSearch Systemd
      ini_file:
        path: "/usr/lib/systemd/system/elasticsearch.service"
        section: Service
        option: LimitMEMLOCK
        value: infinity
        mode: 0644
      notify:
        - reload systemd configuration
        - restart elasticsearch
- name: "修改jvm.options"
  template:
    src: "jvm.options.j2"
    dest: "/etc/elasticsearch/jvm.options"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart elasticsearch
  tags: jvm
- name: "创建elasticsearch目录"
  file:
    path: "{{ item }}"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: "2750"
    state: directory
  with_items:
    - "{{ es_log_dir }}"
    - "{{ es_data_dirs }}"
    - "/etc/elasticsearch/certs"
  tags: dir,dis_certs
- name: "拷贝elasticsearch证书"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
     - {src: '{{ ssl_dir }}/ca.pem', dest: '/etc/elasticsearch/certs/ca.pem'}
     - {src: '{{ ssl_dir }}/{{ ansible_default_ipv4.address }}.key', dest: '/etc/elasticsearch/certs/{{ ansible_hostname }}.key'}
     - {src: '{{ ssl_dir }}/{{ ansible_default_ipv4.address }}.pem', dest: '/etc/elasticsearch/certs/{{ ansible_hostname }}.pem'}
  tags: dis_certs
- name: "修改配置文件"
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart elasticsearch
  tags: conf
