- name: "添加ELK软件源"
  yum_repository:
    file: epel
    name: epel
    description: ELK repository for 7.x packages
    baseurl: "https://mirrors.tuna.tsinghua.edu.cn/elasticstack/7.x/yum/"
    gpgcheck: no
    enabled: yes
  tags: repo
- name: "添加elasticsearch组"
  group:
    name: "elasticsearch"
    gid: "300"
    system: yes
    state: present
  tags: group
- name: "添加elasticsearch用户"
  user:
    name: "elasticsearch"
    uid: "300"
    group: "300"
    createhome: no
    comment: elasticsearch system user
    system: yes
    state: present
  tags: user
- name: "更改系统limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'elasticsearch',limit_type: 'soft',limit_item: 'memlock', value: 'unlimited' }
    - { limit_domain: 'elasticsearch',limit_type: 'hard',limit_item: 'memlock', value: 'unlimited' }
  tags: limits
- name: "修改内核参数"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
    reload: yes
  with_items:
    - {name: 'vm.max_map_count',value: '262144' }
  tags: sysctl
- name: "创建elasticsearch目录"
  file:
    path: "{{ item }}"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: "2750"
    state: directory
  with_items:
    - "{{ es_log_dir }}"
    - "{{ es_data_dirs }}"
  tags: dir
- name: "安装elasticsearch"
  yum:
    name: 'elasticsearch{% if version is defined and version != ""  %}-{{ version }}{% endif %}'
    update_cache: yes
    state: present
- name: "修改ElasticSearch Systemd"
  block:
    - name: ElasticSearch Systemd
      ini_file:
        path: "/usr/lib/systemd/system/elasticsearch.service"
        section: Service
        option: LimitMEMLOCK
        value: infinity
        mode: 0644
      notify:
        - reload systemd configuration
        - restart elasticsearch
- name: "修改jvm.options"
  template:
    src: "jvm.options.j2"
    dest: "/etc/elasticsearch/jvm.options"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart elasticsearch
  tags: jvm
- name: "修改配置文件"
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: "0660"
    force: yes
    backup: yes
  notify: restart elasticsearch
  tags: conf
