- name: fail when hostname is not specified
  fail:
    msg: "hostname not specified"
  when:
    - hostname is not defined
- name: fail when heap size is not specified
  fail:
    msg: "heap_size not specified"
  when:
    - heap_size is not defined
- name: "修改主机名"
  hostname:
    name: "{{ hostname|quote }}"
  tags: hostname
- name: "关闭selinux"
  selinux:
    state: disabled
  tags: selinux
- name: "关闭防火墙"
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  tags: iptables
- name: "更改系统limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'elasticsearch',limit_type: 'soft',limit_item: 'memlock', value: 'unlimited' }
    - { limit_domain: 'elasticsearch',limit_type: 'hard',limit_item: 'memlock', value: 'unlimited' }
  tags: limits
- name: "修改内核参数"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
    reload: yes
  with_items:
    - {name: 'vm.max_map_count',value: '262144' }
  tags: sysctl
